Feature/process
TeamGrowTo/Team-GrowTo-Client pull request #26
Opened 2022-01-16 17:49 UTC by shji023

## 내용
1. 전반적인 기능 구현
- 넘겨받은 카테고리 스킬에 해당하는 태그들 내용 가져오기 -> 일단 api 짜놓고 주석처리함, mockdata 넣고 테스트
- 버튼 선택하여 값 recoill state에 저장
- 뒤로가기 시 에도 이전 값 유지 (버튼 눌려진 상태 표시)
- 모든 속성들을 갯수에 맞게 클릭하여야 다음으로 이동
- 마지막 페이지에서 POST(api 작성하고 주석처리)
- 로딩 페이지 

## 질문
![질문](https://user-images.githubusercontent.com/60960130/149671518-d67caa79-2d75-40f5-a1d2-842328516aef.png)
저 네모 아이콘이 컴포넌트 가려져서 아예 안보여야하는데 컴포넌트 background에 투명도를 줘야해서 줬더니 보이네요 .. 
안보이게 하는 방법 아시나요??

2022-01-18 10:38 UTC, small-j requested changes
process페이지가 하나하나 페이지가 다른데 이걸 state로 빡구현한 영지현을 존경하며..

2022-01-18 10:38 UTC, small-j commented on pages/apis/info.api.ts
> +    return data.data;
우리 get 해올때는 interface로 값 하나하나 풀어서 받기로 했답니다!
귀찮은 작업이긴하지만..ㅠ 그래도 프론트에서 사용하는 데이터를 한번 캡슐화해서 이후에 많은 수정이 필요 없답니답

2022-01-18 10:38 UTC, small-j commented on pages/apis/lectures.api.ts
> +    const { data } = await serverAxios.post(`${PREFIX_URL}/search`, processData, {
오 값을 하나하나 풀어서 넣어주지 않고 이렇게 바로 보내줄수도 있군요

2022-01-18 10:38 UTC, small-j commented on pages/apis/lectures.api.ts
> +      },
이것도 이렇게 전달이 가능하군요

2022-01-18 10:38 UTC, small-j commented on pages/apis/lectures.api.ts
> +    return data.data;
이것두 캡슐화해주면 좋겠어요! 
그리고 백에서 반환받는 데이터가 `data객체 안 -> data 객체`로 감싸여져 이렇게 전달하는건가요?

2022-01-18 10:38 UTC, small-j commented on pages/processPrice/index.tsx
> +      console.log(getTimeData.priceAsc);
불필요한 console.log는 지우면 좋답니다 코드가 깔끔깔끔해져용

2022-01-18 10:38 UTC, small-j commented on pages/processPrice/index.tsx
> +            완료하기 &gt;
&gt말고 아이콘으로 처리하면 크기도 조정할 수 있고 margin도 줄 수 있어서 처리하기 좋을 것 같아요!

2022-01-18 10:38 UTC, small-j commented on pages/processTag/index.tsx
> +import CardTitle from "components/process/CardTitle";
이 파일은 processPrice, processTime과 아주 유사하게 보여서 겹치는 배경과 카드 형태는 컴포넌트화 하고 안에 내용물만 변경해주는 형태로 합쳐주면 좋을것 같네요!! 아무래도 반복되는 css를 계속 적용하게 되면 반응형 때 고쳐야할 부분이 많아지니까요ㅜㅠ

2022-01-18 10:38 UTC, small-j commented on components/process/CardTitle/index.tsx
> +  const te = "마케팅";
변수 이름이 명확하지 않아요!! 하려고 했는데 임시 변수넼ㅋㅋㅋㅋ 넘모 웃긴다

2022-01-18 15:50 UTC, shji023 commented on components/process/CardTitle/index.tsx
> +  const te = "마케팅";
ㅋㅋㅋㅋㅋ지윤이 한테 리코일값 넘겨받으면 바로 없애버릴예정~

2022-01-18 15:50 UTC, shji023 commented on pages/apis/info.api.ts
> +    return data.data;
받아오는 내용이 한개뿐이라 하나하나 풀 필요가 없어서 안했습니다!!

2022-01-18 15:50 UTC, shji023 commented on pages/apis/lectures.api.ts
> +    const { data } = await serverAxios.post(`${PREFIX_URL}/search`, processData, {
서버 연결해봐야알겠지만 일단 ㅎㅎ

2022-01-18 15:50 UTC, shji023 commented on pages/apis/lectures.api.ts
> +      },
api 문서에적혀있길레 써봤어용ㅎㅎ

2022-01-18 15:50 UTC, shji023 commented on pages/apis/lectures.api.ts
> +    return data.data;
캡슐화가 뭔가요...?? 나중에 서버 연결되면 콘솔찍어서 확인해보려구용!!

2022-01-18 15:50 UTC, shji023 commented on pages/processPrice/index.tsx
> +      console.log(getTimeData.priceAsc);
네엥~!

2022-01-18 15:50 UTC, shji023 commented on pages/processPrice/index.tsx
> +            완료하기 &gt;
아이콘으로 처리하면 크기도 조정할 수 있고 margin도 줄 수 있어서 -> 오오  오키 바꿨음~!

2022-01-18 16:09 UTC, small-j commented on pages/processTag/index.tsx
> +import CardTitle from "components/process/CardTitle";
일단 저 index.tsx 파일안의 전체 코드를 말한거긴해! 그 PlayIcon이랑 squreIcon?이 중복되고 있어서 컴포넌트로 만들고 children으로 전달해주면 좋겠다 생각했오!

2022-01-18 16:10 UTC, small-j commented on pages/processTag/index.tsx
> +import CardTitle from "components/process/CardTitle";
내가 저 import 부분을 딱 집어서 해서 헷갈렸겠닼ㅋㅋㅋ

2022-01-18 16:11 UTC, small-j commented on pages/apis/info.api.ts
> +    return data.data;
아하 그랬구만 일단 나는 하나여도 하긴했다! 
어떻게 하면 좋을까??

2022-01-18 16:12 UTC, small-j commented on pages/apis/lectures.api.ts
> +    return data.data;
아하 그 캡슐화는 한번 우리가 변수에 넣어서 프론트에 보내주는 걸 캡슐처럼 한번 감싸줬다는 그런 느낌으로 쓴거야! 
http://wiki.hash.kr/index.php/%EC%BA%A1%EC%8A%90%ED%99%94
이런 느낌으로 표현햇으

2022-01-19 06:33 UTC, shji023 commented on pages/apis/info.api.ts
> +    return data.data;
하나 인데 그 이름이 data여서 data로 받은거긴 하거든?! 하나인데 풀었다는 것은 무슨말인지 이따가 알려줘용 스앵님!!

2022-01-19 06:36 UTC, shji023 commented on pages/processTag/index.tsx
> +import CardTitle from "components/process/CardTitle";
아아 마저 일단 돌아가는거에 중점을 둬가지고 겹치는거 있어도 일단 갈겼엉,,ㅎㅎ
조금씩 공통되는거 묶어주고있는데 시간남으면 더 겹치는거 묶어봐야겟어!!  ㅋㅋㅋㅋㅋ

2022-01-19 13:43 UTC, merged